name: 'Package Lambda Function'
description: 'Simple Lambda function packaging'

inputs:
  lambda-directory:
    description: 'Directory containing Lambda function code'
    required: false
    default: 'lambda'
  output-filename:
    description: 'Name of the output zip file'
    required: false
    default: 'lambda-deployment.zip'

runs:
  using: 'composite'
  steps:
    - name: Package Lambda function
      shell: bash
      run: |
        # Create a temporary directory for Lambda package
        mkdir -p lambda-package
        
        # Copy Lambda function code
        cp ${{ inputs.lambda-directory }}/lambda_function.py lambda-package/
        
        # Install dependencies from lambda requirements.txt
        pip install -r ${{ inputs.lambda-directory }}/requirements.txt --target lambda-package
        
        # Create deployment zip
        cd lambda-package
        zip -r ../${{ inputs.output-filename }} .
        cd ..
        
        echo "Lambda package created: $(ls -lh ${{ inputs.output-filename }})"
        echo "Package contents (first 20 files):"
        unzip -l ${{ inputs.output-filename }} | head -20