name: Deploy Infrastructure

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggers

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions-${{ github.run_id }}
        aws-region: eu-north-1
        audience: sts.amazonaws.com
    
    - name: Verify AWS connection
      run: |
        echo "Connected as:"
        aws sts get-caller-identity
        
    - name: Package Lambda Function
      uses: ./.github/actions/package-lambda
      with:
        lambda-directory: 'lambda'
        output-filename: 'lambda-deployment.zip'
        show-contents: 'true'
    
    - name: Deploy Infrastructure
      uses: ./.github/actions/terraform-deploy
      with:
        action: 'plan-apply'
        terraform-directory: 'terraform'
        auto-approve: 'true'
        show-plan: 'true'
    
    - name: Run Post-Deployment Tests
      uses: ./.github/actions/run-tests
      with:
        test-phase: 'all'
        aws-region: 'eu-north-1'
        verbose: 'true'
