name: Test AWS Connection

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: eu-north-1
    
    - name: Test AWS connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    
    - name: Test Terraform backend
      run: |
        cd terraform
        terraform init
        echo "Terraform backend connection successful!"