name: Test AWS Connection

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggers

permissions:
  id-token: write
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions-${{ github.run_id }}
        aws-region: eu-north-1
        audience: sts.amazonaws.com
    
    - name: Test AWS connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        echo "AWS region: $(aws configure get region)"
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    
    - name: Test Terraform backend
      run: |
        if [ -d "terraform" ]; then
          cd terraform
          terraform init
          echo "Terraform backend connection successful!"
        else
          echo "No terraform directory found, skipping terraform test"
        fi
